export const SET_SINGLE_MOVIE = 'SET_SINGLE_MOVIE';
export const SINGLE_MOVIE_FETCH_START = 'SINGLE_MOVIE_FETCH_START';
export const SINGLE_MOVIE_FETCH_SUCCESS = 'SINGLE_MOVIE_FETCH_SUCCESS';
export const SINGLE_MOVIE_FETCH_ERROR = 'SINGLE_MOVIE_FETCH_ERROR';

export const SET_SIMILAR_MOVIES = 'SET_SIMILAR_MOVIES';

export const SET_WATCHLIST_MOVIES = 'SET_WATCHLIST_MOVIES';
