/* single */
export const SET_SINGLE_MOVIE = 'SET_SINGLE_MOVIE';
export const SINGLE_MOVIE_FETCH_START = 'SINGLE_MOVIE_FETCH_START';
export const SINGLE_MOVIE_FETCH_SUCCESS = 'SINGLE_MOVIE_FETCH_SUCCESS';
export const SINGLE_MOVIE_FETCH_FAIL = 'SINGLE_MOVIE_FETCH_FAIL';
/* single */

/* movies */
export const SET_SIMILAR_MOVIES = 'SET_SIMILAR_MOVIES';
export const SIMILAR_MOVIES_FETCH_START = 'SIMILAR_MOVIES_FETCH_START';
export const SIMILAR_MOVIES_FETCH_SUCCESS = 'SIMILAR_MOVIES_FETCH_SUCCESS';
export const SIMILAR_MOVIES_FETCH_FAIL = 'SIMILAR_MOVIES_FETCH_FAIL';

export const SET_RECOMMENDED_MOVIES = 'SET_RECOMMENDED_MOVIES';
export const RECOMMENDED_MOVIES_FETCH_START = 'RECOMMENDED_MOVIES_FETCH_START';
export const RECOMMENDED_MOVIES_FETCH_SUCCESS = 'RECOMMENDED_MOVIES_FETCH_SUCCESS';
export const RECOMMENDED_MOVIES_FETCH_FAIL = 'RECOMMENDED_MOVIES_FETCH_FAIL';

export const SET_LATEST_MOVIE = 'SET_LATEST_MOVIE';
export const LATEST_MOVIE_FETCH_START = 'LATEST_MOVIE_FETCH_START';
export const LATEST_MOVIE_FETCH_SUCCESS = 'LATEST_MOVIE_FETCH_SUCCESS';
export const LATEST_MOVIE_FETCH_FAIL = 'LATEST_MOVIE_FETCH_FAIL';

export const SET_NOW_PLAYING_MOVIES = 'SET_NOW_PLAYING_MOVIES';
export const NOW_PLAYING_MOVIES_FETCH_START = 'NOW_PLAYING_MOVIES_FETCH_START';
export const NOW_PLAYING_MOVIES_FETCH_SUCCESS = 'NOW_PLAYING_MOVIES_FETCH_SUCCESS';
export const NOW_PLAYING_MOVIES_FETCH_FAIL = 'NOW_PLAYING_MOVIES_FETCH_FAIL';

export const SET_POPULAR_MOVIES = 'SET_POPULAR_MOVIES';
export const POPULAR_MOVIES_FETCH_START = 'POPULAR_MOVIES_FETCH_START';
export const POPULAR_MOVIES_FETCH_SUCCESS = 'POPULAR_MOVIES_FETCH_SUCCESS';
export const POPULAR_MOVIES_FETCH_FAIL = 'POPULAR_MOVIES_FETCH_FAIL';

export const SET_TOP_RATED_MOVIES = 'SET_TOP_RATED_MOVIES';
export const TOP_RATED_MOVIES_FETCH_START = 'TOP_RATED_MOVIES_FETCH_START';
export const TOP_RATED_MOVIES_FETCH_SUCCESS = 'TOP_RATED_MOVIES_FETCH_SUCCESS';
export const TOP_RATED_MOVIES_FETCH_FAIL = 'TOP_RATED_MOVIES_FETCH_FAIL';

export const SET_UPCOMING_MOVIES = 'SET_UPCOMING_MOVIES';
export const UPCOMING_MOVIES_FETCH_START = 'UPCOMING_MOVIES_FETCH_START';
export const UPCOMING_MOVIES_FETCH_SUCCESS = 'UPCOMING_MOVIES_FETCH_SUCCESS';
export const UPCOMING_MOVIES_FETCH_FAIL = 'UPCOMING_MOVIES_FETCH_FAIL';
/* movies */

/* watchlist */
export const SET_WATCHLIST_MOVIE = 'SET_WATCHLIST_MOVIE';
export const SET_WATCHLIST_MOVIES = 'SET_WATCHLIST_MOVIES';

export const WATCHLIST_MOVIE_POST_START = 'WATCHLIST_MOVIE_POST_START';
export const WATCHLIST_MOVIE_POST_SUCCESS = 'WATCHLIST_MOVIE_POST_SUCCESS';
export const WATCHLIST_MOVIE_POST_FAIL = 'WATCHLIST_MOVIE_POST_FAIL';

export const WATCHLIST_MOVIES_FETCH_START = 'WATCHLIST_MOVIES_FETCH_START';
export const WATCHLIST_MOVIES_FETCH_SUCCESS = 'WATCHLIST_MOVIES_FETCH_SUCCESS';
export const WATCHLIST_MOVIES_FETCH_FAIL = 'WATCHLIST_MOVIES_FETCH_FAIL';
export const DELETE_WATCHLIST_MOVIE = 'DELETE_WATCHLIST_MOVIE';
/* watchlist */

/* search */
export const SET_SEARCHED_MOVIES = 'SET_SEARCHED_MOVIES';
export const SEARCH_MOVIES_FETCH_START = 'SEARCH_MOVIES_FETCH_START';
export const SEARCH_MOVIES_FETCH_SUCCESS = 'SEARCH_MOVIES_FETCH_SUCCESS';
export const SEARCH_MOVIES_FETCH_FAIL = 'SEARCH_MOVIES_FETCH_FAIL';
/* search */