/* signle */
export const SET_SINGLE_MOVIE = 'SET_SINGLE_MOVIE';
export const SINGLE_MOVIE_FETCH_START = 'SINGLE_MOVIE_FETCH_START';
export const SINGLE_MOVIE_FETCH_SUCCESS = 'SINGLE_MOVIE_FETCH_SUCCESS';
export const SINGLE_MOVIE_FETCH_FAIL = 'SINGLE_MOVIE_FETCH_FAIL';
/* signle */

export const SET_SIMILAR_MOVIES = 'SET_SIMILAR_MOVIES';

/* watchlist */
export const SET_WATCHLIST_MOVIE = 'SET_WATCHLIST_MOVIE';
export const SET_WATCHLIST_MOVIES = 'SET_WATCHLIST_MOVIES';

export const WATCHLIST_MOVIE_POST_START = 'WATCHLIST_MOVIE_POST_START';
export const WATCHLIST_MOVIE_POST_SUCCESS = 'WATCHLIST_MOVIE_POST_SUCCESS';
export const WATCHLIST_MOVIE_POST_FAIL = 'WATCHLIST_MOVIE_POST_FAIL';

export const WATCHLIST_MOVIES_FETCH_START = 'WATCHLIST_MOVIES_FETCH_START';
export const WATCHLIST_MOVIES_FETCH_SUCCESS = 'WATCHLIST_MOVIES_FETCH_SUCCESS';
export const WATCHLIST_MOVIES_FETCH_FAIL = 'WATCHLIST_MOVIES_FETCH_FAIL';
export const DELETE_WATCHLIST_MOVIE = 'DELETE_WATCHLIST_MOVIE';
/* watchlist */

/* search */
export const SET_SEARCHED_MOVIES = 'SET_SEARCHED_MOVIES';
export const SEARCH_MOVIES_FETCH_START = 'SEARCH_MOVIES_FETCH_START';
export const SEARCH_MOVIES_FETCH_SUCCESS = 'SEARCH_MOVIES_FETCH_SUCCESS';
export const SEARCH_MOVIES_FETCH_FAIL = 'SEARCH_MOVIES_FETCH_FAIL';
/* search */